<?php
/**
 * Use WordPress's Conditional Tags for routing
 *
 * First param is a valid WordPress Conditional Tag. Example: is_front_page, is_single, etc
 * @see https://codex.wordpress.org/Conditional_Tags
 *
 * Second param is the output.
 * Output can be generated by a class method, a closure or a function.
 *
 * Generate output by a Class Method:
 * @example $router->add('is_front_page', ['App\Pages\Home', 'index']);
 *          Result: Invokes App\Pages\Home->index() if is_front_page
 *
 * Generate output by Closure:
 * @example $router->add('is_front_page', function() {
 *              echo 'Home';
 *          });
 *          Result: 'Home' if is_front_page
 *
 * Generate output by Function:
 * @example $router->add('is_front_page', 'doSomething');
 *          Result: Invokes doSomething() if is_front_page
 *
 * In case a route does not match, it will continue WordPress default loading behavior.
 *
 * In case there are multiple conditional tags of the same kind, ex: two is_front_page,
 * the last one will be processed, while the first ones are ignored.
 */
$router->add( 'is_front_page', [ 'App\Pages\Home', 'index' ] );
$router->add( 'is_404', [ 'App\Pages\NotFound', 'index' ] );
