<?php

/** @var $router MWW\Router instance - Don't change it*/
$router = new MWW\Router;

/**
 * Use WordPress's Conditional Tags for routing
 *
 * First param is a valid WordPress Conditional Tag. Example: is_front_page, is_single, etc
 * @see https://codex.wordpress.org/Conditional_Tags
 *
 * Second param is the output.
 * Output can be generated by a class method, a closure or a function.
 *
 * Generate output by a Class Method:
 * @example $router->add('is_front_page', ['App\Pages\HomeController', 'index']);
 *          Result: Invokes App\Pages\HomeController->index();
 *
 * Generate output by Closure:
 * @example $router->add('is_front_page', function() {
 *              echo 'Home';
 *          });
 *          Result: 'Home';
 *
 * Generate output by Function:
 * @example $router->add('is_front_page', 'doSomething');
 *          Result: Invokes doSomething()
 *
 * In case a route does not match, it will continue WordPress default loading behavior.
 *
 * In case there are multiple conditional tags of the same kind, ex: two is_front_page,
 * the first one will be processed, while the latter ones are ignored.
 */
function doSomething() {
    echo 'Something';
}
$router->add('is_front_page', ['App\Pages\HomeController', 'index']);
$router->add('is_front_page', 'doSomething');
$router->add('is_front_page', function() {
    echo 'Closure!';
});